# Generated by Django 2.1.7 on 2019-04-04 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='资源文件名')),
                ('src', models.FileField(upload_to='resources/file', verbose_name='资源文件')),
                ('download_count', models.PositiveIntegerField(verbose_name='下载次数')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '资源文件',
                'verbose_name_plural': '资源文件',
                'ordering': ('-created',),
            },
        ),
    ]
