# Generated by Django 2.1.7 on 2019-04-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='下载次数'),
        ),
    ]
